Joe-Z-School/CSCI3308-MovieMate

ProjectSourceCode/src/views/pages/register.hbs

Created the basic html code for the register form. I gave it the /register action and the method POST- those can be changed if needed though. I didn't do any color styling since we haven't picked a color scheme yet, but I just formatted it to where it at least looks nice. I left the profile icons as colors the user can choose from for now, since we haven't figured out images for them yet.

register form- html code

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/layouts/main.hbs

So now the pages when the certian get and post commands can be seen in the local host 3000. To do this I also updated the main.hbs file so that it included the body and head partials so that eveything could be visible using handlbars.

updated index.js so it can use docker to run in browser

---

ProjectSourceCode/src/init_data/create.sql

I added tables of movies, users, comments, posts, and tables to connect the others. All necessary data criteria is added.

Preliminary create database

---

ProjectSourceCode/src/api/omdbApi.js
ProjectSourceCode/src/config/apiConfig.js

I added some simple dotenv functionality to pull the api key from .env without exposing the key.

added api key fetching to config file

---

ProjectSourceCode/src/api/omdbApi.js

I created a starter structure for the omdbApi class.

created starter api service class

---

ProjectSourceCode/docker-compose.yaml
ProjectSourceCode/src/index.js
ProjectSourceCode/src/init_data/create.sql
ProjectSourceCode/src/views/pages/register.hbs

Had to fix some syntax errors in the create.sql so that the database was properly running, then was able to test and make sure register post function properly working.

Database and Register running properly

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/layouts/main.hbs
ProjectSourceCode/src/views/pages/findFriends.hbs
ProjectSourceCode/src/views/pages/login.hbs
ProjectSourceCode/src/views/partials/head.hbs
ProjectSourceCode/src/views/partials/message.hbs

Made sure and tested login had to adjust a few things to make sure it worked well. Then added a few partials and pages to start helping to build the friends and followers aspect so the user can search for friends they want to follow. Also added the logout feature and authentication.

Updated Login html and post so that they worked together 

---

ProjectSourceCode/package.json
ProjectSourceCode/src/index.js
ProjectSourceCode/src/resources/js/socialScript.js
ProjectSourceCode/src/views/pages/social.hbs
ProjectSourceCode/src/views/partials/head.hbs

Created initial social feed page complete with dynamic post loading and responsive buttons. The social page will load 5 posts at a time to increase the performance of page loading. New posts will be appended to the bottom of the page upon scrolling to the page bottom. Each post currently contains responsive buttons to add/remove a post to the users liked posts, and a different button to add/remove the posted movie to the users WatchList.

Joe - Social Feed Page 

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/pages/login.hbs
ProjectSourceCode/src/views/partials/head.hbs
ProjectSourceCode/src/views/partials/title.hbs

Added title.hbs, updated head.hbs, and made small changes to login html

Added title.hbs 

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/init_data/create.sql
ProjectSourceCode/src/init_data/insert.sql
ProjectSourceCode/src/views/pages/findFriends.hbs
ProjectSourceCode/src/views/pages/notifications.hbs
ProjectSourceCode/src/views/pages/profile.hbs
ProjectSourceCode/src/views/pages/social.hbs
ProjectSourceCode/src/views/partials/nav.hbs

Added the whole request feature of the following so now each followers must be approved or denied. Started setting up the notification feature so that other requests are sent to the notification page for the other user to either approve or deny. Added ways in the index.js to add requests or follows to your account once you are logged in for testing. I also adjusted the insert.sql so that the profile icons were properly put in for our fake data. Added new aspects for the user to confim they want unfollow someone with a modal and same with unrequesting someone. Added some JS on the pages I changed too to have better interface flow to make it smoother for the user. Also did a lot of testing to make sure it all worked.

Add approve/decline follower requests with notifications

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/init_data/create.sql
ProjectSourceCode/src/init_data/insert.sql
ProjectSourceCode/src/views/pages/findFriends.hbs
ProjectSourceCode/src/views/pages/register.hbs

I updated the register/database/find friends pages so that they include a first and last name for each user. I also fixed up the find friends page just a bit so that it looks more cohesive with the rest of the website. I updated the insert.sql page so that everyone has a profile picture and first+last name. 
I made this pull request after fixing some merge conflicts that came up- all of my code was mostly just addition to what was already there, so in the cases where there was a conflict, I kept the code that was there and just added my code to it.

Find friends page revamp

---

ProjectSourceCode/src/api/omdbApi.js
ProjectSourceCode/src/controllers/movieController.js
ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/pages/explore.hbs

Used Maeve's implemented UI and layout for the explore page with my API functionality integrated.

implemented maeve's ui for the explore page

---

ProjectSourceCode/src/index.js

Forgot to add a comma when merging branches earlier

missing comma

---

ProjectSourceCode/src/resources/css/style.css
ProjectSourceCode/src/views/partials/nav.hbs

Fixed a bug with the nav bar where it wouldnt stay uniform across all pages.

Fixed a bug with the nav bar

---

ProjectSourceCode/src/resources/css/style.css
ProjectSourceCode/src/views/partials/footer.hbs

Created the partial for the footer and added some CSS.

Created partial for the footer

---

ProjectSourceCode/.gitignore
ProjectSourceCode/src/index.js

Changed the host variable in index.js to pull from the .env file so Render can correctly pair the web service to the database.

Render hosting changes

---

ProjectSourceCode/src/views/pages/social.hbs

Just did some debugging and reworking of logic

Fix modal comment submission and auto-refresh issues

---

ProjectSourceCode/src/index.js

Removed the extra route to /watchlist so instead watchlist is now located from Neha's /profile/watchlist route instead. Added description field retrieval to /profile/watchlist so watchlist items can reference the movie description.

Fixed user profile watchlist details

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/init_data/create.sql
ProjectSourceCode/src/resources/js/messagingScript.js
ProjectSourceCode/src/views/pages/profile.hbs
ProjectSourceCode/src/views/pages/social.hbs

Created the posting modal from the users profile page. Posting modal allows the user to upload their own images, use the poster image of the movie from their watchlist, add a post title, optional movie title and description, user comments, a rating on a scale of 1 to 5, and the platform in which they watched the movie from.

Social post modal

---

ProjectSourceCode/src/views/pages/profile.hbs

Fixed the bug where the modal window didn't fully close after the post button was pushed on the modal by refreshing profile page.

Fixed bug with modal not closing fully when post data sent'

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/pages/profile.hbs
ProjectSourceCode/src/views/pages/social.hbs
ProjectSourceCode/src/views/partials/postDetailsModal.hbs

Added the post information to the social page cards with all the post information. Added the initial post cards to profile page to display posts made by user, and their likes/comment counts.

Social and Profile Cards Information Display

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/pages/register.hbs
ProjectSourceCode/src/views/pages/watchlist.hbs

For watchlist now you can't remove movies from other profiles. For register, email must be in correct format

Watchlist and Register bug fixed

---

ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/pages/profile.hbs
ProjectSourceCode/src/views/partials/postDetailsModal.hbs

Created and loaded modals onto the profile page that gathers the information from each social post a user has made and displays it in a linear form.

Changes to post details on profile page

---

ProjectSourceCode/src/controllers/movieController.js
ProjectSourceCode/src/index.js
ProjectSourceCode/src/views/pages/explore.hbs
ProjectSourceCode/src/views/pages/movieDetails.hbs

Removed unnecessary review and watched button logic and fixed tabButton querying.

Removing redundant code

---

ProjectSourceCode/src/views/pages/movieDetails.hbs

Removed references to review routes.

removed references to review routes

---

ProjectSourceCode/src/views/pages/findFriends.hbs
ProjectSourceCode/src/views/pages/social.hbs

Now it looks like everyhting is updated and responsive!

updated find friends page and button so responsive
